### ISSUE TITLE
Marketplace Settings: Stewards -  System is showing up as a user that can be assigned orgs and should not appear

### ISSUE THREAD

**Issue by mparizernc** [aml-development/ozp-center#127]
I have seen this with both H2 (file) and mariaDB, when I go to Marketplace Settings and the Stewards tab the System user appears as a user that can be assigned orgs. The system user should not appear on the list of users that can be assigned orgs.

**Comment by akonsowski** [comment]
is this still an issue? i was not able to reproduce on LS

**Comment by lsemesky** [comment]
I am also not able to reproduce. Are you able to reproduce @tdressel ?

**Comment by tdressel** [comment]
Checked in Center Settings | Stewards Tab 
RESULTS - System is no longer listed as a user.

**Comment by tdressel** [comment]
Passed on Staging.
