### ISSUE TITLE
QuickView Modal | Administration Tab displays for non admin users.

### ISSUE THREAD

**Issue by tdressel** [aml-development/ozp-center#439]
Administration Tab still displays on Staging. ***Works on Lowside***

STR-
Pre-Req-
Go to Group Admin page and take away Admin and Org Steward privileges
Go to Apps Mall homepage on staging
Drill into an app
RESULTS - Administration tab displays
EXPECTED RESULTS - Administration tab should NOT display.

**Comment by clarkjefcoat** [comment]
If this is something that we can't reproduce on the development servers, we have to assume this is an issue with the staging or production environments.  That means that this will not be fixed by a change to the source code.

**Comment by akonsowski** [comment]
when groups are added to a user they have to refresh their session for the privileges to be updated. If their admin privileges are revoked they will be able to access the admin tab, however they will not be able to perform any admin actions.

**Comment by tdressel** [comment]
Passed on Latest.

**Comment by tdressel** [comment]
Passed on 2PI test.  Needs testing on Staging.

**Comment by tdressel** [comment]
Passed on staging.
