### ISSUE TITLE
Change default Listing types to be the same 5 as AML

### ISSUE THREAD

**Issue by bhalt** [aml-development/ozp-center#455]
Ozone should match AML Listing types as the default setting in order to streamline help documentation.

**Comment by wski** [comment]
@bhalt could you outline this a bit more? We're a bit confused about what work is required.

**Comment by bhalt** [comment]
Currently the listing types in the AML Center dropdown are filler -- and not the same as the customer version. You'll have to get the list from somebody with access to the customer version (it's unclass) and then it's just a text change @wski

**Comment by rkenyon1969** [comment]
@mannyrivera2010 

What is the status? - thanks,

**Comment by mannyrivera2010** [comment]
@rkenyon1969 - Is this a setting in a ozp-center configuration file?

**Comment by lsemesky** [comment]
Awaiting list from someone with access. Have contacted people with access as suggested by Russ

**Comment by tdressel** [comment]
Listing Type filters now display Web Application, Widget, Desktop App, Web Services, Code Library. Passed on Latest.

**Comment by tdressel** [comment]
Still only 3 on Staging. ( Web application, widget and developer resources)

**Comment by lsemesky** [comment]
@skhtet @blynch11p take a look at this pull request. The same changes may need to be made on staging.

**Comment by tdressel** [comment]
Passed on Staging. IE10, FF 31 and Chrome 36
