### ISSUE TITLE
Tabbing through the carousel causes the previous/next buttons to move awkwardly in front of apps and out of alignment

### ISSUE THREAD

**Issue by tdressel** [aml-development/ozp-center#524]
Tabbing through the carousel causes the previous/next buttons to move awkwardly in front of apps and out of alignment

**Comment by wski** [comment]
Can you find a way to reproduce this LS? If not it's going to be impossible for most of us to address.

**Comment by lsemesky** [comment]
> Can you find a way to reproduce this LS? If not it's going to be impossible for most of us to address.

Seconded.

**Comment by lsemesky** [comment]
After discussion with Tiff there is no way for me actually work on this issue since it is HS only. Moving to backlog.

**Comment by blynch11p** [comment]
This is reproducible on LS. I showed @akonsowski this morning.
Most of the time, the Arrows/buttons just disappear from the carousel, but sometimes they shift away from their correct positioning.

**Comment by tdressel** [comment]
I was able to recreate in FF34.

**Comment by tdressel** [comment]
Passed on Staging. IE10, FF 31 and Chrome 36
