### ISSUE TITLE
notification module is not constrained to the screen

### ISSUE THREAD

**Issue by dylankolson** [aml-development/ozp-center#624]
When the user has many notifications the drop down exceeds the screen space at the bottom. This makes it hard to scroll within the drop down and click see more. 

Current:
![screen shot 2016-05-18 at 11 07 07 am](https://cloud.githubusercontent.com/assets/10820108/15364267/e3304626-1ce9-11e6-8fcd-c4784dda4ec0.png)

Ideal?
![screen shot 2016-05-18 at 11 21 36 am](https://cloud.githubusercontent.com/assets/10820108/15364489/c3ec6a5a-1cea-11e6-963d-51c3b5369b75.png)

**Comment by wski** [comment]
@bhalt how should we handle this? Do we want to limit it to like 3 notifications or something?

**Comment by bhalt** [comment]
Yes.. My vote would be 2-3 max @wski

**Comment by bhalt** [comment]
Also, has a word count limit been implemented on the dropdown yet? Now that the word count has expanded on notifications inside the modal, the dropdown message should cutoff with an "..." after a few lines. We don't want entire notifications shown in the dropdown. @wski

**Comment by wski** [comment]
It hasn't I planned to add that when @mannyrivera2010 gets around to increasing the limit on the backend. I'll go ahead and limit the count of notifications, would you like me to toss a word limit and add the ellipsis at the end. What should this limit be?

**Comment by wski** [comment]
First part done here https://github.com/ozone-development/ozp-react-commons/pull/59

**Comment by bhalt** [comment]
Maybe keep the dropdown character limit to what the notification used to be before the expansion?

**Comment by wski** [comment]
150 was the previous limit, However I found a bug inadvertently; If a notification has no spaces, it looks like this: ![image here](http://i.imgur.com/poBES5l.png)

**Comment by bhalt** [comment]
@wski can you add `word-wrap: break-word;` to `.UserNotification` in ozp-react-commons? That should fix that...

**Comment by wski** [comment]
Yeah, and I'll set the drop down limit to 150 chars. Perhaps we should do some other css magic to remove line breaks.

**Comment by tdressel** [comment]
I added 10 new notifications and one with a lot of words.  Looks good.

**Comment by tdressel** [comment]
Mistake in previous test.. This fails on Staging and Master. ( DI2E is down so cant verify on latest)
Test Case #1
STR-
Go to Center Settings | Notifications
Create a really long 150 char notification without spaces.
Send
RESULTS - Notifications are truncated in Navigation bar | Notifications drop down
EXPECT RESULTS - Notifications should word wrap.

**Comment by rkenyon1969** [comment]
@wski - what is the status on this?

**Comment by tdressel** [comment]
Test Case 1 - Failed
Test Case 2 - Passed

**Comment by tdressel** [comment]
passed on Latest.

**Comment by tdressel** [comment]
Passed on Staging - IE, FF and Chrome
