### ISSUE TITLE
Administration tab time / date changes

### ISSUE THREAD

**Issue by wski** [aml-development/ozp-center#660]
In the Administration tab for listings, under Listing Changes, we currently show increments of mins, hours, days, weeks, months, or years in the timeline.  It would be helpful to have a date reflected when last activity is beyond a day.

**Comment by akonsowski** [comment]
@wski was this fixed by #663? can we move this to resolved?

**Comment by tdressel** [comment]
date is listed beyond minutes and hours.

**Comment by tdressel** [comment]
Staging IE, FF and Chrome
Steps used to test:
Go to Pop Up Details | Administration Tab | Listing Changes
RESULTS - This now displays a date.
