### ISSUE TITLE
IE- Start Tour upon log in is not prompting.

### ISSUE THREAD

**Issue by tdressel** [aml-development/ozp-center#670]
STR-
Clear cache/browser
Exit out of IE and open IE
RESULTS - Tour does not launch
EXPECTED RESULTS - Tour should launch.

**Comment by lsemesky** [comment]
@akonsowski - How do we reproduce/resolve IE defects?

**Comment by akonsowski** [comment]
the team had access to browser stack but recently it has not been working so right now we have no way to test and work on IE bugs

**Comment by akonsowski** [comment]
i just tested this and i am not able to reproduce this bug.

**Comment by tdressel** [comment]
works on latest.

**Comment by tdressel** [comment]
Passes on staging
