### ISSUE TITLE
Typeahead library causes warnings

### ISSUE THREAD

**Issue by rpokorny** [aml-development/ozp-center#676]
Steps to reproduce:

1. Run `npm run build`
Expected results: no warnings in output
Actual Results: The following warnings appear:

ERROR in ./app/js/utils/typeahead.js

/home/rpokorny/Documents/center-ui/app/js/utils/typeahead.js
    84:25  error  Expected a conditional expression and instead saw an assignment  no-cond-assign
   313:21  error  Expected a conditional expression and instead saw an assignment  no-cond-assign
   339:20  error  Expected a conditional expression and instead saw an assignment  no-cond-assign
   360:20  error  Expected a conditional expression and instead saw an assignment  no-cond-assign
   434:21  error  Expected a conditional expression and instead saw an assignment  no-cond-assign
   994:21  error  Expected a conditional expression and instead saw an assignment  no-cond-assign
  1175:21  error  Expected a conditional expression and instead saw an assignment  no-cond-assign
  1181:21  error  Expected a conditional expression and instead saw an assignment  no-cond-assign
  1183:28  error  Expected a conditional expression and instead saw an assignment  no-cond-assign
  1558:25  error  Empty block statement

This was reported to me by a community member.

**Comment by wski** [comment]
Check that the `.eslintignore` is working, It seemed to have been working earlier but perhaps it's not loading the ignore file during tests.

**Comment by wski** [comment]
Fixed in https://github.com/ozone-development/ozp-center/pull/677

**Comment by tdressel** [comment]
Passed on Staging.
