### ISSUE TITLE
Pop Up Details | REVIEW TAB | Edit icon is available to other users 

### ISSUE THREAD

**Issue by tdressel** [aml-development/ozp-center#679]
STR-
Log on as basic user
Go to App with reviews (the reviews have to be made by someone else)
RESULTS- Edit icon is available.
EXPECTED RESULTS - Edit icon shouldn't be available to anyone but the reviewer.

The problem with this is that the user can edit the review and when they submit it .......it doesn't save the edited version.

**Comment by tdressel** [comment]
Edit icon only displays for current user's review.
Edit icon displays for all reviews when logged in as admin.

**Comment by akonsowski** [comment]
admins should be able to view other users reviews only for the purpose to delete them

**Comment by tdressel** [comment]
Passed on Latest.  Test admin, reviewer and non reviewer.

**Comment by tdressel** [comment]
Tested and works with 2pI user.  Needs testing with 1st party user.

**Comment by tdressel** [comment]
Passed on Staging.
