### ISSUE TITLE
model quick view is showing admin tabs for normal users

### ISSUE THREAD

**Issue by akonsowski** [aml-development/ozp-center#681]
in reference to [#201](https://github.com/aml-development/ozp-backend/issues/201)
new changes to the backend that obscure the usernames of users cause normal users to be able to view the administrative tabs of any listing.

**Comment by tdressel** [comment]
Doesn't show tabs for admin users but there were other test cases we needed to address in order to restrict access to users that cannot be org stewards or admins.   
#687

**Comment by tdressel** [comment]
2PI users cant see Admin.  Needs testing with 1st party Admin

**Comment by tdressel** [comment]
Passed on Staging.
