### ISSUE TITLE
'npm run build' fails

### ISSUE THREAD

**Issue by cstepnitz** [aml-development/ozp-center#685]
Any guesses?

$ npm run build

> center-ui@1.1.35 build C:\Users\cstepnitz\ozp2\ozp-center-release-1.1.35
> NODE_ENV="production" gulp build

'NODE_ENV' is not recognized as an internal or external command,
operable program or batch file.

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
npm ERR! node v4.4.7
npm ERR! npm  v2.15.8
npm ERR! code ELIFECYCLE
npm ERR! center-ui@1.1.35 build: `NODE_ENV="production" gulp build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the center-ui@1.1.35 build script 'NODE_ENV="production" gulp build'.
npm ERR! This is most likely a problem with the center-ui package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     NODE_ENV="production" gulp build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs center-ui
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls center-ui
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\cstepnitz\ozp2\ozp-center-release-1.1.35\npm-debug.log

**Comment by rpokorny** [comment]
I don't think they support windows.

**Comment by chazzlabs** [comment]
@cstepnitz If you haven't addressed this already, you can replace ```NODE_ENV="production" gulp build``` in package.json with ```set NODE_ENV=production&& gulp build``` on Windows.

**Comment by akonsowski** [comment]
has this issue been resolved?

**Comment by chazzlabs** [comment]
@akonsowski It appears that ```package.json``` hasn't been updated to address Windows/Linux compatibility, so I'd say in that sense the issue is not resolved.  But if the official answer is "ozp-center development doesn't support Windows" then I think that should be documented in order for this to be considered resolved.  For what it's worth, I changed ```package.json``` locally to address this particular issue but ran into other issues when trying to run ozp client projects on Windows.

**Comment by akonsowski** [comment]
I documented this in [Developer Setup](https://github.com/aml-development/ozp-documentation/wiki/Developer_Setup) for future reference.

**Comment by rkenyon1969** [comment]
thanks
