### ISSUE TITLE
Reviews - Instructions to reviewer

### ISSUE THREAD

**Issue by clarkjefcoat** [aml-development/ozp-center#686]
The text may need to be changed on the reviews screen for Tailored Views.  Please discuss if we need to change the "Data entered must NOT ..." text in

![reviews](https://cloud.githubusercontent.com/assets/7015118/17446723/97c4271c-5b18-11e6-8e88-6cce378280b6.png)

**Comment by lsemesky** [comment]
@rkenyon1969  who do I talk to about the requirements for this?

**Comment by rkenyon1969** [comment]
@lsemesky - please discuss with Soe and get input from cleared team members like Tiff, Brian and Gary.

**Comment by lsemesky** [comment]
After discussions with Soe,
Basic idea is that we want reviews to be able to be viewed by all regardless of access level so we need to change this to say that the review should be UFOUO

**Comment by akonsowski** [comment]
after discussing with Mark we came to the conclusion that the text should read no higher than FOUO. this could change at a later date to add bootstrap classify but for the time being this will be sufficient

**Comment by lsemesky** [comment]
@blynch11p

**Comment by tdressel** [comment]
Passed on latest.

**Comment by tdressel** [comment]
Passed on Staging.
