### ISSUE TITLE
2PI- Organization Filters reflect the wrong count 

### ISSUE THREAD

**Issue by tdressel** [aml-development/ozp-center#688]
STR-
Log on as 2PI user
Go to Organization filters
RESULTS - The count does not reflect the accurate restricted amount of listings displayed to 2PI user.  Instead it displays the overall count of listings available to all restricted/nonrestricted users. This is confusing.If the filter count displays 90 listings but the results display 10 because 80 are restricted. 
EXPECTED RESULTS - This filter count should match the amount of listings displayed in results.

**Comment by wski** [comment]
This sounds like it should be a backend thing. If we are getting a higher count that would mean that the 2PI user could actually see all of the filters.

**Comment by mannyrivera2010** [comment]
logic located in ozpcenter/api/listing/model_access.py method: 
````python
def put_counts_in_listings_endpoint(queryset):
    .....
````

**Comment by rkenyon1969** [comment]
@mannyrivera2010 - what is the status?

**Comment by tdressel** [comment]
This is fixed on Staging.
