### ISSUE TITLE
add private listings to create edit listing

### ISSUE THREAD

**Issue by akonsowski** [aml-development/ozp-center#704]
add private listings to create edit listing

**Comment by tdressel** [comment]
Passed on Latest.
On QuickView Details | Admin Tab
Edit Form
Submit form

STR-
Log on as aaronson (miniluv)
Submit a Listing with Private Listing Setting enabled.
Save and Publish
Log on as julia (miniluv) org steward
Go to All Listings / Ministry of Love Listings
RESULTS - Private Listing displays and has a "lock icon".
Open the Listing
QuickView Modal | Admin Tab displays lock icon.

**Comment by tdressel** [comment]
Passed on Latest.

**Comment by tdressel** [comment]
Need to wait for EDE.

**Comment by tdressel** [comment]
Passed on Staging.
