### ISSUE TITLE
2PI- Security Banner reflecting incorrectly for 2PI Users

### ISSUE THREAD

**Issue by tdressel** [aml-development/ozp-center#709]
See Soe or Tiffany for explanation.

**Comment by tdressel** [comment]
Apps Mall should reflect the highest security banner of current user not of highest security marking in app.

**Comment by lsemesky** [comment]
@skhtet will need to look at the logic for "Apps Mall should reflect the highest security banner of current user not of highest security marking in app." 

Best I could do was update it to show a different banner for second party users.

**Comment by tdressel** [comment]
Needs testing on Staging.

**Comment by tdressel** [comment]
Confirmed working for 2PI user on Staging.
