### ISSUE TITLE
Bug(Images): Investigate images taking longer to load in Center and Hud

### ISSUE THREAD

**Issue by rkenyon1969** [aml-development/ozp-center#713]

**Comment by rkenyon1969** [comment]
"For the last few months there appears to be an increase in the tim it takes for images to load. This has been noticed in both Center and Hud" - Mark Shoemaker

**Comment by wski** [comment]
Not a frontend issue. This is a networking issue that is out of our control. (there has been no code added that would slow the loading of images.) Please consider caching within the infrastructure the system is deployed on.

**Comment by tdressel** [comment]
Needs to be tested on Staging.

**Comment by tdressel** [comment]
Will improve once on C2S.
