### ISSUE TITLE
Increase tag maximum length to 30

### ISSUE THREAD

**Issue by lsemesky** [aml-development/ozp-center#719]
Current listing tag is a maximum of 16 characters. Make the new limit 30 and update the UI to reflect the new maximum

**Comment by tdressel** [comment]
Tested on Latest.  Used 16 , 30 and 60 chars. It gave a user friendly error when trying to save more than 30 and allowed me to save listing when I saved 30 or less.

**Comment by tdressel** [comment]
Passed on Staging.
