### ISSUE TITLE
Tab Flow Indicator

### ISSUE THREAD

**Issue by mleeBoeing** [aml-development/ozp-center#847]
Modify "No Thanks" button to depict when the user has tabbed to. Similar to "Start the Tour" button turns blue once focused on. See attached images.

![image](https://user-images.githubusercontent.com/26389772/30084125-22fa36fe-925f-11e7-800d-5079bab7345f.png)![image](https://user-images.githubusercontent.com/26389772/30084118-1c0e87f0-925f-11e7-8989-5c52e5eaec10.png)

**Comment by flesher1** [comment]
Added class to commons.scss so that the "No thanks" and "End Tour" buttons turned blue like the "Start the tour" button.
