### ISSUE TITLE
Clicking on Help from some screens doesn't navigate to help screen.

### ISSUE THREAD

**Issue by lsemesky** [aml-development/ozp-center#860]
STR (Steps to Reproduce)-
Go to Homepage
Click on Listing Management
Choose Help Menu Icon
RESULTS - Navigates user to homepage
EXPECTED RESULTS - Should open Help Modal. 
****This also happens on Center Settings Screen, and Submit/Edit Listing Form

**Comment by flesher1** [comment]
Modifications made. https://github.com/aml-development/ozp-center/compare/center_style_fixes 

No pull request yet.
