### ISSUE TITLE
User profile displays deleted Listings

### ISSUE THREAD

**Issue by mleeBoeing** [aml-development/ozp-center#865]
STR-
Log into Apps Mall as WSmith
Go to Menu | Profile 
RESULTS - All owners listings display. For example AirMail displays
Log on as bigbrother
Delete Airmail
Verify it is deleted and not in pending for deletion status.
Log on as wsmith
Go to Menu | Profile
RESULTS - All owners listing display.  Air Mail still displays.
EXPECTED RESULTS - Air Mail shouldn't display since it was deleted.

**Comment by flesher1** [comment]
Done. no PR yet.

**Comment by flesher1** [comment]
Merged.
