### ISSUE TITLE
Launch Application feature doesn't display sys/usage requirements in pop up when launched from thumbnail

### ISSUE THREAD

**Issue by mleeBoeing** [aml-development/ozp-center#903]
AMLNG-798

STR-
Pre-req - Define system and usage requirements in an App Listing.  In Profile Settings , Enable the option Show Launch Requirements Notice
Go to Homepage
From Thumbnail view, Launch App from thumbnail view
RESULTS - Sys/Usage requirements pop up displays without the actual system / usage requirements.
EXPECTED RESULTS - Sys/usage requirements from pre-requisites should display on the this pop up.
Open Quick View Modal
Launch App
RESULTS - Sys/usage requirements from the prerequisites display on the pop up as they should.

**Comment by irizvifearless** [comment]
Resolved with PR 904 https://github.com/aml-development/ozp-center/pull/904
